name: main

on:
  push:
    branches:
      - main

env:
  GIST_ID: 715c62717519f634185af0ebde234992

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ci
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      - run: npm run build
      - run: sed -i '0,/index.js/s//dist\/index.js/' action.yml package.json
      - run: rm -rf test/data
      - uses: ./
        with:
          gist-id: ${{ env.GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}
